<?php

/**
 * @file
 * The RDF Skos module.
 */

declare(strict_types = 1);

use Drupal\field\FieldStorageConfigInterface;

/**
 * Implements hook_field_views_data_alter().
 *
 * Ensure that the Views filters based on the SKOS entity reference field type
 * use the SkosConceptReferenceId filter plugin.
 */
function rdf_skos_field_views_data_alter(array &$data, FieldStorageConfigInterface $field_storage) {
  if ($field_storage->getType() !== 'skos_concept_entity_reference') {
    return;
  }

  foreach ($data as $table_name => $table_data) {
    foreach ($table_data as $field_name => $field_data) {
      if (isset($field_data['filter']) && $field_name != 'delta') {
        $data[$table_name][$field_name]['filter']['id'] = 'skos_concept_reference_id';
      }
    }
  }
}
